name: Publish to Pypi
on:
  workflow_dispatch:
    inputs:
      pypi_repo:
        description: 'Repo to upload to (testpypi or pypi)'
        default: 'testpypi'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9.*"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -r requirements-dev.txt
    - name: Build distribution
      run: python setup.py sdist
    - name: Publish MLexp to TestPyPI
      uses: pypa/gh-action-pypi-publish@v1
      with:
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
      if: ${{ github.event.inputs.pypi_repo == 'testpypi' }}
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
      if: ${{ github.event.inputs.pypi_repo == 'pypi' }}