name: Publish To (Test)PyPi and create GitHub release

on:
  push:
    tags:
      - "v*.*.*"
      - "test*.*.*"

jobs:
  build_dist:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9.*"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[torch]
        pip install -r requirements-dev.txt
        pip install twine
    - name: Build distribution
      run: python setup.py sdist
    - name: Check whether long description will render correctly on PyPi
      run: twine check dist/*
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
      if: startsWith(github.ref, 'refs/tags/v')



  publish_testpypi:

    runs-on: ubuntu-latest
    needs: [build_dist]
    if: startsWith(github.ref, 'refs/tags/test')

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Publish MLexp to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

  publish_pypi:

    runs-on: ubuntu-latest
    needs: [build_dist, publish_pypi]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Publish MLexp to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          password: ${{ secrets.PYPI_TOKEN }}

  create_release:

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*