name: Testing

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:

    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            code:
              - 'mlexp/**'
              - 'test/**'
              - '.github/**'
              - 'requirements.txt'
              - 'requirements-dev.txt'
      - name: Set up Python 3.9.*
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.*"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements-dev.txt
      - name: Start mlflow server
        if: steps.filter.outputs.code == 'true'
        run: |
          mlflow server &
          sleep 30s
      - name: Setting neptune api token
        if: steps.filter.outputs.code == 'true'
        run: |
          echo "NEPTUNE_API_TOKEN=${{ secrets.NEPTUNE_API_TOKEN }}" >> $GITHUB_ENV
      - name: Test code and docs
        if: steps.filter.outputs.code == 'true'
        run: |
          coverage run -m pytest --neptune_project ${{ secrets.NEPTUNE_PROJECT }}
          coverage xml -i
      - name: Test Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: steps.filter.outputs.code == 'true'
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: True
          thresholds: '75 90'
          hide_branch_rate: True
          hide_complexity: True
          format: 'markdown'
          output: 'both'
      - name: Add test coverage report to PR comments
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && steps.filter.outputs.code == 'true'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Add test coverage report to job summary
        if: steps.filter.outputs.code == 'true'
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      - name: Test docs
        if: steps.filter.outputs.code == 'false'
        run: |
          pytest tests/test_docs --neptune_project ${{ secrets.NEPTUNE_PROJECT }}