name: Testing

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            code:
              - 'mlexp/**'
              - 'test/**'
            any:
              - '**'
      - name: Set up Python 3.9.*
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.*"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements-dev.txt
      - name: Start mlflow server
        run: |
          mlflow server &
          sleep 30s
      - name: Setting neptune api token
        run: |
          echo "NEPTUNE_API_TOKEN=${{ secrets.NEPTUNE_API_TOKEN }}" >> $GITHUB_ENV
      - name: Test code and docs
        if: steps.filter.outputs.code == 'true'
        run: |
          pytest --neptune_project ${{ secrets.NEPTUNE_PROJECT }}
      - name: Test docs
        if: steps.filter.outputs.code == 'false'
        run: |
          pytest tests/test_docs --neptune_project ${{ secrets.NEPTUNE_PROJECT }}